### PR TITLE
Upgrade the omnibus install when version changes.

### PR DESCRIPTION
**Pull request by robbkidd**
The chef_ingredient install action was _not_ installing a newer version
of the omnibus package if a newer version was declared.

### CODE REVIEW

**Comment by nellshamrell** [comment]
🚀 🍰

**Comment by irvingpop** [comment]
Apologies it's been a while since I dug into the underlying logic.  Could you imagine this change doing anything unexpected to existing users of the cookbook?

**Comment by robbkidd** [comment]
I don't think it will add any more unexpected things than before we updated this cookbook to use the new chef_ingredient. Before, it was `action :install` with an APT or YUM package resource which was in effect an upgrade. chef_ingredient now—unless a custom repo recipe is given—remote_file downloads the supermarket omnibus package from packages.chef.io and installs via `dpkg` or `rpm`. In testing on Ubuntu with a version specified in `node['supermarket_omnibus']['package_version']`, this cookbook would _not_ install a newer version than what is already installed on a node without changing the action to `:upgrade`.

**Comment by irvingpop** [comment]
Good to know!  👍

**Comment by robbkidd** [comment]
Thanks for your eyeballs, @irvingpop!

**Pull request merged**
