### PR TITLE
Require Chef 12.5+ and remove compat_resource / fancyexecute depedencies

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by irvingpop** [comment]
Looks like the deprecation error is coming from my `fancy_execute` cookbook: 

```
"Chef::Platform.set is deprecated (CHEF-13)/opt/kitchen/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:64:in `block in <top (required)>'.\nPlease see https://docs.chef.io/deprecations_chef_platform_methods.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.26/lib/chef/formatters/doc.rb:419:in `deprecation'"
```

I think we can safely remove fancy_execute from the dependencies list, since equivalent or better functionality has existed in Chef since 12.6.0:  https://github.com/chef/chef/commit/c03d49c7cc3b5eb351abc9f6537a1a65692e93fc

**Comment by irvingpop** [comment]
Weird - apparently only the centos6 image doesn't appear to resolve its own fqdn correctly:

```
NoMethodError
        -------------
        undefined method `downcase' for nil:NilClass
        
        Cookbook Trace:
        ---------------
          /var/opt/supermarket/cache/cache/cookbooks/omnibus-supermarket/attributes/default.rb:64:in `from_file'
        
        Relevant File Content:
        ----------------------
        /var/opt/supermarket/cache/cache/cookbooks/omnibus-supermarket/attributes/default.rb:
        
         57:  # ## Top-level attributes
         58:  #
         59:  # These are used by the other items below. More app-specific top-level
         60:  # attributes are further down in this file.
         61:  
         62:  # The fully qualified domain name. Will use the node's fqdn if nothing is
         63:  # specified.
         64>> default['supermarket']['fqdn'] = node['fqdn'].downcase
         65:  
         66:  # The URL for the Chef server. Used with the "Chef OAuth2 Settings" and
         67:  # "Chef URL Settings" below. If this is not set, authentication and some of the
         68:  # links in the application will not work.
         69:  default['supermarket']['chef_server_url'] = nil
         70:  
         71:  default['supermarket']['config_directory'] = '/etc/supermarket'
         72:  default['supermarket']['install_directory'] = '/opt/supermarket'
         73:  default['supermarket']['app_directory'] = "#{node['supermarket']['install_directory']}/embedded/service/supermarket"
```

**Comment by vinyar** [comment]
Bump on removing fancy_execute.

**Comment by irvingpop** [comment]
hey @tas50 given that node['fqdn'] isn't 100% reliable, how would you feel about changing that line?

**Comment by robbkidd** [comment]
[Great success in centos-6](https://travis-ci.org/chef-cookbooks/supermarket-omnibus-cookbook/jobs/221073252) with Supermarket v3.0.1 currently pulled from the current channel instead of stable.

We've got a unit test to fix about the downloaded file expectation.

@tas50 @irvingpop Question: should I switch the tests back to testing with the latest `stable` package or keep the tests using the latest `current` package?

**Comment by robbkidd** [comment]
With the upgraded chef-ingredient using custom resources, the [stubbing in the spec](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/blob/master/spec/unit/libraries/supermarket_server_spec.rb#L109) around what file gets downloaded no longer works. I'm not sure testing chef-ingredient is necessary, so we can probably remove that spec.

**Comment by tas50** [comment]
@robbkidd it's probably fair to remove that

**Comment by robbkidd** [comment]
💚

**Comment by robbkidd** [comment]
How much of a version bump do y'all think this warrants?

**Comment by tas50** [comment]
I bump majors when I remove support for older clients

**Pull request merged**
