### PR TITLE
collaborators feature on by default

### PR DESCRIPTION
**Pull request by jeremymv2**
### Description

The purpose of this change is to make the Collaborator Groups feature enabled by default.
I cannot think of any downsides to making it the default.

### Issues Resolved

N/A

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

Signed-off-by: Jeremy J. Miller <jm@chef.io>

### CODE REVIEW

**Comment by irvingpop** [comment]
I'm 👍  but looks like there's Rubocop failures that need to be cleaned up

**Comment by robbkidd** [comment]
Collaborator Groups was a feature we were letting bake in private Supermarkets. Though I suppose at baking for a year, it's probably time to consider the feature's defaultyness.

I'm not certain it's something we want to turn on for public Supermarket in the feature's current form or we'll face another namespace problem with group names.

**Comment by irvingpop** [comment]
@jeremymv2 now looks like the ChefSpec tests are failing because they need to be updated to with the new features :)  https://travis-ci.org/chef-cookbooks/supermarket-omnibus-cookbook/jobs/185237984#L342

**Comment by jeremymv2** [comment]
@robbkidd @irvingpop  Sorry, I went on PTO and was fully checked out.  Back in the swing of things and the build is green!

**Comment by nellshamrell** [comment]
This looks good.  We plan on leaving the collaborator_groups feature as disabled in public Supermarket for now (as I REALLY don't want to introduce another namespacing yak shave right now), but it is fine to enable it by default for other Supermarkets.  Since we already overwrite the 'features' attribute in public Supermarket, I don't think making it the default will have any negative effect.

**Pull request merged**
