### PR TITLE
[JEX-116] Use a version of chef-ingredient that points to packages.chef.io.

### PR DESCRIPTION
**Pull request by yzl**
Update to a version of `chef-ingredient` that installs packages from `packages.chef.io`:

* Note that `chef-ingredient` by default no longer installs from package repos.
* Added the attribute `node['supermarket_omnibus']['custom_repo_recipe']` to allow users to specify installation from their own package repositories.
* It is expected that `chefdk` > 0.12.0 will contain `mixlib-install` ~> 1.0; at that point, it will be safe to stop bundle-installing `mixlib-install` to run tests on travis.ci and instead use the `mixlib-install` from `chefdk`.

cc @nellshamrell @robbkidd @irvingpop @chef-cookbooks/engineering-services @tas50 @iennae

### CODE REVIEW

**Comment by schisamo** [comment]
👍 overall. Is it possible to marke bb9ff3dc9263cc5dc77865e83cbed795135e5072 as WIP/TEMP until the next ChefDK ships? I believe that will have the correct version of mixlib-install.

**Comment by scotthain** [comment]
👍 codewise!

**Comment by sersut** [comment]
👍

**Comment by yzl** [comment]
@schisamo Done; I updated the commit message and added a note to the PR description.

**Comment by irvingpop** [comment]
👍 awesome!

**Comment by robbkidd** [comment]
👍

**Pull request merged**
