### PR TITLE
update metadata.rd license

### PR DESCRIPTION
**Pull request by chilicheech**
So the it matches the license that's in the LICENSE file.

### CODE REVIEW

**Comment by robbkidd** [comment]
You are absolutely correct.

gif-keyboard-10387241933456068150

**Comment by irvingpop** [comment]
👍 thank you @chilicheech !

**Comment by robbkidd** [comment]
Yes indeed! Working through fixing the tests over on #43.

**Comment by robbkidd** [comment]
Or possibly #44!

**Comment by tas50** [comment]
Fixed in #44

**Pull request closed without merging**
